### ISSUE TITLE
The app defaults to testnet and does not remember the user selected network

### ISSUE THREAD

**Issue by Netherdrake** [reef-defi/reef-app#113]
https://app.reef.io currently defaults to testnet, and resets to testnet after each new load. 

This is obviously not a desired behavior for end users (it should default to mainnet, as well as persist user preferences in local storage).

**Comment by Frenkiee** [comment]
The current app stores users selected network. So every time they reload a page it will boot up the same. 

If for example app always loads on mainnet, testnet URLs won't work. 

Therefore I would mark this issue as closed

**Comment by Netherdrake** [comment]
I think Matjaz fixed it
