### ISSUE TITLE
Pools list: Smarter action buttons

### ISSUE THREAD

**Issue by lukalocniskar** [reef-defi/reef-app#120]
On pools list we would like to guide user through the flow of providing liquidity. 

1. If user doesn't have tokens to provide liq. to a pool, we should show the trade button to get him started.
2. If user have tokens to provide liq. to a pool, show withdraw button. 
3. If user have LP tokens to withdraw from liq. pool show withdraw button. 
4. If user have any of the required tokens show trade button.

**Comment by Netherdrake** [comment]
Why so complicated? Also why assume what action the user wants, what if they want to add more liquidity instead of withdrawing, or maybe they just want to trade?

**Comment by samoslag** [comment]
Implemented.
