### ISSUE TITLE
Change UI message for pools and staking

### ISSUE THREAD

**Issue by lukalocniskar** [reef-defi/reef-app#121]
Staking
- Change "Staking" in main menu and dashboard to "Bonds"

Pools - Provide
- Change tab "Provide" to "Stake"
- Add description to that form "Earn trading fees on this liquidity pool by staking your tokens into it"
- Change "Provide" button to "Stake"

Pools - Withdraw
- Change tab "Withdraw" to "Unstake"
- Change "Withdraw" button to "Unstake"

**Comment by samoslag** [comment]
Implemented.
