### ISSUE TITLE
Dashboard tabs

### ISSUE THREAD

**Issue by samoslag** [reef-defi/reef-app#147]
- Tokens - always present
- Bonds - contains only bonds with user's funds staked. Hide tab if there's none to be displayed.
- NFTs - contains user's NFTs. Hide tab if user doesn't have any NFTs.

**Comment by Netherdrake** [comment]
No, dont hide the tabs, especially not bonds.

**Comment by Netherdrake** [comment]
For NFT's, if the list is empty, show CTA to get NFT's on Sqwid

**Comment by samoslag** [comment]
Understood. Do we have any specific links for NFTs or just [Squid](https://sqwid.app/)?

**Comment by Netherdrake** [comment]
Just sqwid for now. So maybe can make a nice call to action just for them

**Comment by samoslag** [comment]
Added Sqwid CTA, kept all tabs as they were.
