### ISSUE TITLE
Swap/Send amount clipping

### ISSUE THREAD

**Issue by Netherdrake** [reef-defi/reef-app#160]
![Screenshot from 2022-08-31 00-01-55](https://user-images.githubusercontent.com/3516903/187551712-5b6f0e0c-69e3-4d60-81d6-fd4bb24f0031.png)

**Comment by samoslag** [comment]
Applied solution: Balance over 1.000.000 will be displayed in human readable format (1.500.000 -> 1.5 M). Native tooltip will still display unformatted amount.
