### ISSUE TITLE
NFT images are not loading

### ISSUE THREAD

**Issue by Netherdrake** [reef-defi/reef-app#162]
<img width="588" alt="Screenshot 2022-09-01 at 10 38 30 PM" src="https://user-images.githubusercontent.com/3516903/188007895-a7e22630-1359-4cf0-ad29-f3711c77e91e.png">

This was broken in https://github.com/reef-defi/reef-app/commit/52db9f935bd04e133ca11849415dd63ebbc8f73b

**Comment by matjazonline** [comment]
Fixed
